In [2]:
import numpy as np

In [3]:
a = np.full(10,0.)
a[4] = 1

In [4]:
b = np.arange(10,50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [5]:
c = np.arange(9).reshape(3,3)
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
d = np.random.random(size=(3,3,3))
d

array([[[0.56175597, 0.29570904, 0.79615834],
        [0.24909691, 0.56864419, 0.80442293],
        [0.46017529, 0.62120485, 0.25211254]],

       [[0.4004696 , 0.30861711, 0.57472476],
        [0.07170656, 0.95223012, 0.78951585],
        [0.77203443, 0.28325861, 0.17986995]],

       [[0.37803186, 0.59112436, 0.10051705],
        [0.20746136, 0.8910256 , 0.89562076],
        [0.76726067, 0.36255037, 0.36251455]]])

In [7]:
e = np.random.random(size=30)
e.mean()

0.4753446194165809

In [14]:
mid_score = [10,20,30]
final_score = [70,80,90]

mid_score = np.array(mid_score)
final_score = np.array(final_score)

total_score = mid_score + final_score
total_score

array([ 80, 100, 120])

In [27]:
array_a = np.arange(10)
array_b = np.array(range(10))
array_c = np.arange(0,10,2)
print(array_a)
print(array_b)
print(array_c)
print(array_c.shape, array_c.ndim, array_c.dtype, array_c.size, array_c.itemsize) # 원소의 데이터 크기 (Byte)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
(5,) 1 int32 5 4


In [32]:
salary = np.array([220, 250, 230])
salary = salary + 100
salary

In [34]:
salary = salary * 2
salary

array([640, 700, 660])

In [67]:
players=[[170,76.4],[183,86.2],[171,73.5],[176,80.1]]
np_players = np.array(players)
print(np_players[np_players[:,1] >= 80])
print(np_players[np_players[:,0] >= 180])

[[183.   86.2]
 [176.   80.1]]
[[183.   86.2]]


In [96]:
revenue_in_yen = np.random.randint(100,300,30)
revenue_in_yen

array([185, 164, 173, 133, 151, 120, 208, 175, 157, 188, 290, 107, 229,
       137, 141, 271, 171, 237, 196, 239, 282, 165, 182, 156, 132, 114,
       189, 151, 197, 185])

In [100]:
won_array = revenue_in_yen * 9.70
won_array

array([1794.5, 1590.8, 1678.1, 1290.1, 1464.7, 1164. , 2017.6, 1697.5,
       1522.9, 1823.6, 2813. , 1037.9, 2221.3, 1328.9, 1367.7, 2628.7,
       1658.7, 2298.9, 1901.2, 2318.3, 2735.4, 1600.5, 1765.4, 1513.2,
       1280.4, 1105.8, 1833.3, 1464.7, 1910.9, 1794.5])

In [112]:
revenue_in_doller = np.random.randint(10,20,30)
won_array2 = revenue_in_doller * 1391
won_array2

array([18083, 22256, 20865, 15301, 13910, 13910, 20865, 23647, 13910,
       18083, 26429, 13910, 15301, 25038, 15301, 22256, 13910, 15301,
       26429, 15301, 13910, 20865, 25038, 23647, 15301, 20865, 20865,
       15301, 20865, 22256])

In [122]:
ta = won_array+won_array2
ta = ta.astype("int64")
ta[ta < 20000]

array([19877, 16591, 15374, 15074, 15432, 19906, 14947, 17522, 16668,
       15568, 17599, 17619, 16645, 16581, 16765], dtype=int64)