In [2]:
import numpy as np

In [3]:
# numpy.ndarray 
# N차원 배열 , 정수형 색인 설정 가능, 같은 유형의 데이터를 저장

list1 = [1,2,3,4,5]
arr = np.array(list1)
arr

arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
# 원소 개수 통일
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# 배열 크기
print(arr1.shape)
print(arr2.shape)


(5,)
(2, 3)


In [6]:
# 배열 전체의 요소 개수
print(arr1.size)
print(arr2.size)

5
6


In [10]:
# 배열 데이터 타입 확인
arr1.dtype

dtype('int32')

In [13]:
# 배열의 차원 확인
print(arr1.ndim)
print(arr2.ndim)

1
2


In [29]:
arr3 = np.array([[[1,2,3,4],
                  [1,2,3,4],
                  [1,2,3,4]],
                 
                 [[1,2,3,4],
                  [1,2,3,4],
                  [1,2,3,4]]])
print(arr3.ndim)
print(arr3.shape)
print(arr3.size)

3
(2, 3, 4)
24


In [31]:
arr_zeros = np.zeros((3,4))
arr_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
arr_ones = np.ones((3,4), dtype= int)
arr_ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [41]:
arr_full = np.full((5,5),10)
arr_full

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [42]:
arr = np.array(range(1,51))
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])