In [1]:
import numpy as np

In [2]:
a = np.full(10,0.)
a[4] = 1

In [3]:
b = np.arange(10,50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [4]:
c = np.arange(9).reshape(3,3)
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
d = np.random.random(size=(3,3,3))
d

array([[[0.41875435, 0.1467061 , 0.32677995],
        [0.77461296, 0.31744298, 0.33156326],
        [0.2660874 , 0.68880167, 0.8225672 ]],

       [[0.45554914, 0.85429323, 0.89902107],
        [0.83041714, 0.36008937, 0.51475841],
        [0.04793546, 0.97995595, 0.682712  ]],

       [[0.56501393, 0.52336807, 0.45968066],
        [0.73863866, 0.15364385, 0.06493311],
        [0.93877482, 0.77604786, 0.72933625]]])

In [6]:
e = np.random.random(size=30)
e.mean()

0.4597530945152347

In [7]:
mid_score = [10,20,30]
final_score = [70,80,90]

mid_score = np.array(mid_score)
final_score = np.array(final_score)

total_score = mid_score + final_score
total_score

array([ 80, 100, 120])

In [8]:
array_a = np.arange(10)
array_b = np.array(range(10))
array_c = np.arange(0,10,2)
print(array_a)
print(array_b)
print(array_c)
print(array_c.shape, array_c.ndim, array_c.dtype, array_c.size, array_c.itemsize) # 원소의 데이터 크기 (Byte)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
(5,) 1 int32 5 4


In [9]:
salary = np.array([220, 250, 230])
salary = salary + 100
salary

array([320, 350, 330])

In [10]:
salary = salary * 2
salary

array([640, 700, 660])

In [11]:
players=[[170,76.4],[183,86.2],[171,73.5],[176,80.1]]
np_players = np.array(players)
print(np_players[np_players[:,1] >= 80])
print(np_players[np_players[:,0] >= 180])

[[183.   86.2]
 [176.   80.1]]
[[183.   86.2]]


In [12]:
revenue_in_yen = np.random.randint(100,300,30)
revenue_in_yen

array([175, 175, 267, 288, 198, 297, 128, 167, 123, 185, 231, 110, 201,
       162, 117, 190, 168, 212, 145, 207, 184, 252, 263, 177, 277, 231,
       133, 227, 123, 221])

In [13]:
won_array = revenue_in_yen * 9.70
won_array

array([1697.5, 1697.5, 2589.9, 2793.6, 1920.6, 2880.9, 1241.6, 1619.9,
       1193.1, 1794.5, 2240.7, 1067. , 1949.7, 1571.4, 1134.9, 1843. ,
       1629.6, 2056.4, 1406.5, 2007.9, 1784.8, 2444.4, 2551.1, 1716.9,
       2686.9, 2240.7, 1290.1, 2201.9, 1193.1, 2143.7])

In [14]:
revenue_in_doller = np.random.randint(10,20,30)
won_array2 = revenue_in_doller * 1391
won_array2

array([26429, 22256, 19474, 22256, 19474, 23647, 26429, 23647, 25038,
       18083, 19474, 22256, 18083, 25038, 20865, 25038, 18083, 15301,
       15301, 26429, 23647, 25038, 15301, 18083, 16692, 23647, 25038,
       25038, 16692, 23647])

In [15]:
ta = won_array+won_array2
ta = ta.astype("int64")
ta[ta < 20000]

array([19877, 19712, 17357, 16707, 17852, 19799, 19378, 17885],
      dtype=int64)

In [16]:
arr = np.arange(2,51,2)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

In [17]:
arr = np.zeros((4,4))
print(arr)
arr = np.full((10,10),1)
print(arr)
arr = np.arange(0,28).reshape(7,4)
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]


In [18]:
arr = np.arange(3,101,3)
arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [19]:
print(arr.size)
print(arr.reshape(3,11))
print(arr.reshape(3,11).size)

33
[[ 3  6  9 12 15 18 21 24 27 30 33]
 [36 39 42 45 48 51 54 57 60 63 66]
 [69 72 75 78 81 84 87 90 93 96 99]]
33


In [20]:
import random

In [52]:
print(np.random.rand(6,4))
arr = np.random.randint(1,100,size=(5,5))
print(arr)
print(arr.astype("float64"))

[[0.31079165 0.0092977  0.63500308 0.81859506]
 [0.76100516 0.57741685 0.78871584 0.46973598]
 [0.24967044 0.63835685 0.13336453 0.8338536 ]
 [0.88315608 0.73208774 0.72728076 0.85930775]
 [0.02494525 0.99511112 0.2932743  0.46823928]
 [0.23146832 0.17939022 0.9198914  0.15625378]]
[[50 70 27 49 28]
 [90 96 68 96  2]
 [37 84 87 63 76]
 [30  6 50 28 14]
 [70 69  4 61  7]]
[[50. 70. 27. 49. 28.]
 [90. 96. 68. 96.  2.]
 [37. 84. 87. 63. 76.]
 [30.  6. 50. 28. 14.]
 [70. 69.  4. 61.  7.]]


In [27]:
x = np.arange(10).reshape(2,5)
print(x[:,3:])
print(x[1,1:4])

[[3 4]
 [8 9]]
[6 7 8]


In [45]:
y=np.arange(15).reshape(3,5)
print(y[:,3:4])
print(y[1,:])
print(y[:2,1:4])

[[ 3]
 [ 8]
 [13]]
[5 6 7 8 9]
[[1 2 3]
 [6 7 8]]


In [50]:
y = np.arange(1,13).reshape(3,4)
print(y[y<=5])
y[y % 3 == 0]

[1 2 3 4 5]


array([ 3,  6,  9, 12])

In [60]:
x = np.random.randint(1, 100, size = 10)
print(x[x % 2 == 0])
print(x[x >= 60])

[66 40 76 12 52 14]
[66 76 85]


In [63]:
print(x[(x > 30) & (x < 70)])
print(x[(x > 60) | (x % 2 != 0)])

[66 40 52 53]
[66  7 76 25 53 85]


In [65]:
temp = np.array(
        [23.9, 24.4, 24.1, 25.4, 27.6, 29.7,
         26.7, 25.1, 25.0, 22.7, 21.9, 23.6, 
         24.9, 25.9, 23.8, 24.7, 25.6, 26.9, 
         28.6, 28.0, 25.1, 26.7, 28.1, 26.5, 
         26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])
len(temp)

31

In [78]:
print(temp[temp> 25.0].size)
print(np.mean(temp[temp > 25]))

21
26.857142857142858
