In [1]:
import numpy as np

In [2]:
# numpy.ndarray 
# N차원 배열 , 정수형 색인 설정 가능, 같은 유형의 데이터를 저장

list1 = [1,2,3,4,5]
arr = np.array(list1)
arr

arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
# 원소 개수 통일
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# 배열 크기
print(arr1.shape)
print(arr2.shape)


(5,)
(2, 3)


In [5]:
# 배열 전체의 요소 개수
print(arr1.size)
print(arr2.size)

5
6


In [6]:
# 배열 데이터 타입 확인
arr1.dtype

dtype('int32')

In [7]:
# 배열의 차원 확인
print(arr1.ndim)
print(arr2.ndim)

1
2


In [8]:
arr3 = np.array([[[1,2,3,4],
                  [1,2,3,4],
                  [1,2,3,4]],
                 
                 [[1,2,3,4],
                  [1,2,3,4],
                  [1,2,3,4]]])
print(arr3.ndim)
print(arr3.shape)
print(arr3.size)

3
(2, 3, 4)
24


In [9]:
arr_zeros = np.zeros((3,4))
arr_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
arr_ones = np.ones((3,4), dtype= int)
arr_ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [11]:
arr_full = np.full((5,5),10)
arr_full

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [12]:
arr = np.array(range(1,51))
arr = np.arange(1,51)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [13]:
arr = np.arange(1,51,10.5)
arr

array([ 1. , 11.5, 22. , 32.5, 43. ])

In [14]:
arr = np.random.rand(2,3)
arr

array([[0.56645817, 0.65193139, 0.17708215],
       [0.30354494, 0.61596855, 0.28115943]])

In [15]:
arr = np.random.randint(2,10)
print(arr)
arr = np.random.randint(2,10, size=(2,3))
arr

8


array([[8, 9, 9],
       [4, 5, 4]])

In [16]:
arr_type = np.array([1.2, 2.3, 3.4], dtype=np.int64)
arr_type

array([1, 2, 3], dtype=int64)

In [17]:
arr_type = arr_type.astype("float64")
arr_type

array([1., 2., 3.])

In [18]:
arr = np.array([1,2,3])
print(arr+arr)
print(arr*arr)

[2 4 6]
[1 4 9]


In [19]:
arr2_a = np.array([[1,2,3],[4,5,6]])
arr2_b = np.array([[7,8,9],[10,11,12]])

print(arr2_a+arr2_b)
print(arr2_a-arr2_b)

[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]


In [20]:
print(arr2_a +3)
print(arr2_a *2)

[[4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]]


In [21]:
arr_1 = np.arange(0,6)
arr_1[2]

2

In [22]:
arr_2 = np.array([range(1,4),range(4,7)])

print(arr_2[0])
print(arr2[1,0])
print(arr2[1,2])
print(arr2[1])

[1 2 3]
4
6
[4 5 6]


In [23]:
arr1 = np.arange(10)
arr1[3:8]

array([3, 4, 5, 6, 7])

In [24]:
arr1[3:8] = range(10,15)
arr1

array([ 0,  1,  2, 10, 11, 12, 13, 14,  8,  9])

In [25]:
arr2 = np.arange(0,50).reshape(5,10)
print(arr2[:2, :])
print(arr2[:, 0])
print(arr2[:4, :5])
print(arr2[2][1],arr2[4,8],arr2[2,9],arr2[1,2])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[ 0 10 20 30 40]
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]]
21 48 29 12


In [26]:
score = np.array([80,75,55,96,30])
score >=80

array([ True, False, False,  True, False])

In [27]:
score[score >=80]

array([80, 96])

In [28]:
name = np.array(["영화", "동원", "성우", "수민"])
bol = np.array([False,True,False,True])
name[bol]

array(['동원', '수민'], dtype='<U2')

In [29]:
score = np.array([[60,60],[70,70],[80,80],[90,90]])
score
name == "영화"

array([ True, False, False, False])

In [30]:
score[name == "동원"]

array([[70, 70]])

In [31]:
arr = np.random.randint(1, 10, size=(2,5))
print(arr)
print(arr.sum())
print(np.sum(arr))

[[5 8 9 7 7]
 [6 9 3 8 5]]
67
67


In [32]:
print(arr.mean())
print(np.mean(arr))

6.7
6.7


In [33]:
arr = np.arange(1,6)
print(np.sqrt(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [34]:
arr = np.array([-1,-2,-3,-4,-5])
np.abs(arr)

array([1, 2, 3, 4, 5])

In [37]:
arr = np.array([1,10,5,8,2,4,3,6,8,7,9])
np.sort(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [39]:
np.sort(arr)[::-1]

array([10,  9,  8,  8,  7,  6,  5,  4,  3,  2,  1])

In [54]:
arr2d=np.array([[5,6,7,8],
              [4,3,2,1],
              [10,9,12,11]])

In [55]:
np.sort(arr2d, axis=1) # 열 정렬

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [56]:
np.sort(arr2d, axis=0) # 행 정렬

array([[ 4,  3,  2,  1],
       [ 5,  6,  7,  8],
       [10,  9, 12, 11]])

In [89]:
y = np.random.randint (100,size=(3,5))
print(y.mean(), y.sum(), y.max(), y.min(), y.var(), np.median(y), y.std())
# 평균, 합계, 최대, 최소, 분산 np.var(), 중앙값 np.median(), 표준 편차 np.std()

56.8 852 97 8 642.2933333333333 65.0 25.343506729206464


In [59]:
data = np.loadtxt("height_weight.txt", delimiter = ",") # delimiter : 구분기호
data

array([[175.2, 180.3, 175. , 169.2, 185.2, 188. , 177.6, 178.2, 177. ,
        179. ],
       [ 65.6,  88. ,  79.2,  69.3,  55. ,  71.2,  73. ,  68.9,  74. ,
         82. ]])

In [60]:
data.shape

(2, 10)

In [62]:
height_cm = data[0]
weight_kg = data[1]


In [64]:
height_m = height_cm / 100


In [67]:
BMI = weight_kg/(height_m**2)
BMI

array([21.37153104, 27.07018468, 25.86122449, 24.20652885, 16.03543423,
       20.14486193, 23.14392095, 21.69720651, 23.62028791, 25.59220998])

In [72]:
data = np.loadtxt("ratings.txt",delimiter = "::", dtype="int")
data

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]])

In [99]:
print(data.shape, data.ndim, data.size)

(1000209, 4) 2 4000836


In [77]:
print(data[data[:,0] == 1])

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]
 [        1      1197         3 978302268]
 [        1      1287         5 978302039]
 [        1      2804         5 978300719]
 [        1       594         4 978302268]
 [        1       919         4 978301368]
 [        1       595         5 978824268]
 [        1       938         4 978301752]
 [        1      2398         4 978302281]
 [        1      2918         4 978302124]
 [        1      1035         5 978301753]
 [        1      2791         4 978302188]
 [        1      2687         3 978824268]
 [        1      2018         4 978301777]
 [        1      3105         5 978301713]
 [        1      2797         4 978302039]
 [        1      2321         3 978302205]
 [        1       720         3 978300760]
 [        1      1270         5 978300055]
 [        1

In [90]:
user_id = data[:,0]
ratings = data[:,2]
ratings.mean()

3.581564453029317

In [98]:
data[data[:,0] == 1,2].mean()

4.188679245283019